### ISSUE TITLE
Can't pass the ios build on xCode

### ISSUE THREAD

**Issue by SamuelGuNUAA** [Aerobotics/react-native-dji-mobile#123]
Hi,
Thanks for your work on this library. I am building an ios version app with this library, following the instructions, but still blocked by some build issues in xCode and need you help as I just start with the ios stuff.

I am using:
react-nativve: 0.59.9
react-native-dji-mobile: 0.3.11
xCode: 10.2.1

I set below as in GettingStarted.md:
**1. in podfile**
**a. add "use_modular_headers!"
b. set "** 
pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', **:modular_headers => false**
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', **:modular_headers => false**
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', **:modular_headers => false**
**pod 'DJIWidget', '~> 1.5', :modular_headers => true**
pod 'react-native-dji-mobile', :path => '../node_modules/react-native-dji-mobile'"
**(pod install successfully)**

**2. Created 'empty.swift' at the same level as the Info.plist**
**Run build in xCode, but get 'Apple Mach-O Linker Error' as below (just list some the errors):**

"_OBJC_CLASS_$_DJIFlightControllerKey", referenced from:
objc-class-ref in libreact-native-dji-mobile.a(DJIMissionControl.o)
objc-class-ref in libreact-native-dji-mobile.a(DJIMobile.o)
objc-class-ref in libreact-native-dji-mobile.a(DJIRealTimeDataLogger.o)
objc-class-ref in libreact-native-dji-mobile.a(VirtualStickTimelineElement.o)
"_OBJC_CLASS_$_DJIWaypoint", referenced from:
objc-class-ref in libreact-native-dji-mobile.a(WaypointMissionTimelineElement.o)
"_DJIFlightControllerParamIsUltrasonicBeingUsed", referenced from:
function signature specialization <Arg[1] = Dead> of react_native_dji_mobile.VirtualStickTimelineElement.(isUltrasonicEnabled in _9A648512620641238644E54D7118CAA8)(withCompletion: (Swift.Bool, Swift.Error?) -> ()) -> () in libreact-native-dji-mobile.a(VirtualStickTimelineElement.o)
"_DJICameraParamVideoFileCompressionStandard", referenced from:
react_native_dji_mobile.CameraControlNative.setVideoFileCompressionStandard(videoCompressionStandard: Swift.String, resolve: (Any?) -> (), reject: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-dji-mobile.a(CameraControl.o)
"_OBJC_CLASS_$_DJISDKManager", referenced from:
objc-class-ref in libreact-native-dji-mobile.a(DJIMedia.o)
objc-class-ref in libreact-native-dji-mobile.a(CameraControl.o)
objc-class-ref in libreact-native-dji-mobile.a(DroneVideoView.o)
objc-class-ref in libreact-native-dji-mobile.a(DJIMissionControl.o)
objc-class-ref in libreact-native-dji-mobile.a(DJIMobile.o)
objc-class-ref in libreact-native-dji-mobile.a(DJIRealTimeDataLogger.o)
objc-class-ref in libreact-native-dji-mobile.a(RecordFlightData.o)
...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Google and tried to change 'Mach-O Type' from 'Executable' to 'Static Library' can resolve these errors, but cause another error as:**
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/usr/lib/libz.tbd is not an object file (not allowed in a library)``

Will be appreciate if anyone can advise how I could move on as well as any specific settings in xCode, (i.e. enable Bitcode => disable, Mach-O Type => ?, etc.)

**Comment by arosendorff** [comment]
Hi Samuel,

Sorry you're having set up issues! Could you please post your whole Podfile here? Also, do you have the `DJI-SDK-iOS` dependency in your Podfile? Try adding `pod 'DJI-SDK-iOS', '~> 4.10'` if it isn't there.

Our set up documentation can definitely use a bit of reworking and updating, hopefully we can work out your problem and add it to the docs!

**Comment by SamuelGuNUAA** [comment]
Hi Adam,

Here is the Podfile fails,

    # Uncomment the next line to define a global platform for your project
    platform :ios, '9.0'
    react_native_path = '../node_modules/react-native'

    target 'AppName' do
    use_modular_headers!
    rn_path = '../node_modules/react-native'

    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
      'Core',
      'DevSupport', # Devmenu
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'CxxBridge'
    ]

    pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'react-native-maps', path: '../node_modules/react-native-maps'
    pod 'react-native-google-maps', path: '../node_modules/react-native-maps'  # Remove this line         
        if you don't want to support GoogleMaps on iOS
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
    pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
    # Third party deps
    pod 'DoubleConversion', :podspec => react_native_path + '/third-party-            
    podspecs/DoubleConversion.podspec', :modular_headers => false

    pod 'glog', :podspec => react_native_path + '/third-party-podspecs/glog.podspec',     
    :modular_headers => false

    pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec',  :modular_headers => false

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'react-native-orientation-locker', :path => '../node_modules/react-native-orientation- 
    locker/react-native-orientation-locker.podspec'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

    pod 'react-native-gps-state', :path => '../node_modules/react-native-gps-state'

    pod 'lottie-ios', :path => '../node_modules/lottie-ios'

    pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

     pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'DJIWidget', '~> 1.5', :modular_headers => true
    pod 'react-native-dji-mobile', :path => '../node_modules/react-native-dji-mobile'
    end

    post_install do |installer|
    installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
    end
    end


By adding **pod 'DJI-SDK-iOS', '~> 4.10'**, compile fails in Xcode, so is there any specific configurations?

**Comment by SamuelGuNUAA** [comment]
For my project, just resolved by,
1.  add $(SRCROOT)/../node_modules/react-native-nfc-manager/ios to Header Search Paths
2. remove those DJI's recommended settings
