### ISSUE TITLE
Implement media download

### ISSUE THREAD

**Issue by mcorner** [Aerobotics/react-native-dji-mobile#44]
I have had poor luck with downloading movies using the SDK in the past, but maybe I missed something.

**Comment by arosendorff** [comment]
I have got it working before, transferring images off the drone :)

 We will look into implementing this in the not too distant future, but feel free to give it a shot if you're feeling motivated! 😄

**Comment by mcorner** [comment]
I needed it for downloading videos, but even with the sample app it is just too slow (1`hr for a 2.4GB video).  I just noticed the DJI GO app won't even download videos at all.  So I need to implement something with direct access to the sd card instead.

**Comment by arosendorff** [comment]
Ah yes, I think that'll be a limitation with the SDK and Ocusync!
